{% set name = "Squidpy" %}
{% set version = "1.8.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: bc6b92079e983a0e9fa6843f1fae73f8c8f83d9e2d03decf43ee3cdf57a504dd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8.1
    - anndata >=0.9
    - cycler >=0.11.0
    - dask-image >=0.5.0
    - dask[array] >=2021.02.0,<=2024.11.2
    - docrep >=0.3.1
    - fsspec >=2021.11.0
    - matplotlib-scalebar >=0.8.0
    - matplotlib-base >=3.3.0
    - networkx >=2.6.0
    - numba >=0.56.4
    - numpy >=1.23.0
    - omnipath >=1.0.7
    - pandas >=2.1.0
    - Pillow >=8.0.0
    - scanpy >=1.9.3
    - scikit-image >=0.20
    - scikit-learn >=0.24.0
    - statsmodels >=0.12.0
    - tifffile !=2022.4.22
    - tqdm >=4.50.2
    - validators >=0.18.2
    - xarray >=2024.10.0
    - zarr >=3.0.0
    - spatialdata >=0.6.0
    - spatialdata-plot

test:
  imports:
    - squidpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/squidpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Spatial Single Cell Analysis in Python
  description: |
    Squidpy is a tool for the analysis and visualization of spatial molecular data.
    It builds on top of Scanpy and AnnData, from which it inherits modularity and scalability.
    It provides analysis tools that leverages the spatial coordinates of the data,
    as well as tissue images if available.
  doc_url: https://squidpy.readthedocs.io
  dev_url: https://github.com/scverse/squidpy

extra:
  recipe-maintainers:
    - giovp
    - melonora
    - timtreis
    - LucaMarconato
