{% set name = "Squidpy" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 46c3235c43e7e3aeec4f76e800aa51c723d9f182c4c834c44dce818f8052f92f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - aiohttp >=3.8.1
    - anndata >=0.9
    - cycler >=0.11.0
    - dask-image >=0.5.0
    - dask >=2021.02.0
    - docrep >=0.3.1
    - fsspec >=2021.11.0
    - leidenalg >=0.8.2
    - matplotlib-scalebar >=0.8.0
    - matplotlib-base >=3.3.0
    - networkx >=2.6.0
    - numba >=0.56.4
    - numpy >=1.23.0
    - omnipath >=1.0.7
    - pandas
    - Pillow >=8.0.0
    - scanpy >=1.9.3
    - scikit-image >=0.20
    - scikit-learn >=0.24.0
    - statsmodels >=0.12.0
    - tifffile !=2022.4.22
    - tqdm >=4.50.2
    - validators >=0.18.2
    - xarray >=2023.12.0
    - zarr >=2.6.1
    - spatialdata >=0.2.5
    - ome-zarr >=0.8.4
  run_constrained:
    - napari[pyqt5] ==0.4.15
    - pydantic ==1.10.13

test:
  imports:
    - squidpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/squidpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Spatial Single Cell Analysis in Python
  description: |
    Squidpy is a tool for the analysis and visualization of spatial molecular data.
    It builds on top of Scanpy and AnnData, from which it inherits modularity and scalability.
    It provides analysis tools that leverages the spatial coordinates of the data,
    as well as tissue images if available.
  doc_url: https://squidpy.readthedocs.io
  dev_url: https://github.com/scverse/squidpy

extra:
  recipe-maintainers:
    - giovp
    - michalk8
